# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Add a comment or note to a HaloITSM ticket"


class Input:
    TICKET_ID = "ticket_id"
    NOTE_HTML = "note_html"
    OUTCOME = "outcome"
    WHO_CAN_VIEW_ID = "who_can_view_id"
    NOTE_TYPE_ID = "note_type_id"


class Output:
    TICKET = "ticket"
    SUCCESS = "success"


class AddCommentInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "ticket_id": {
      "type": "integer",
      "title": "Ticket ID",
      "description": "ID of the ticket to add comment to",
      "order": 1
    },
    "note_html": {
      "type": "string",
      "title": "Note Content",
      "description": "HTML content of the note/comment to add",
      "order": 2
    },
    "outcome": {
      "type": "string",
      "title": "Outcome",
      "description": "Outcome text for the note",
      "order": 3
    },
    "who_can_view_id": {
      "type": "integer",
      "title": "Who Can View ID",
      "description": "ID indicating who can view this note (1=public, 2=agents only, etc.)",
      "default": 1,
      "order": 4
    },
    "note_type_id": {
      "type": "integer",
      "title": "Note Type ID",
      "description": "Type of note to create (1=standard note, 2=outcome, etc.)",
      "default": 1,
      "order": 5
    }
  },
  "required": [
    "ticket_id",
    "note_html"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class AddCommentOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "ticket": {
      "$ref": "#/definitions/ticket",
      "title": "Ticket",
      "description": "The updated ticket details",
      "order": 1
    },
    "success": {
      "type": "boolean",
      "title": "Success",
      "description": "Whether the comment was successfully added",
      "order": 2
    }
  },
  "required": [
    "ticket",
    "success"
  ],
  "definitions": {
    "ticket": {
      "type": "object",
      "title": "Ticket",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "Ticket ID",
          "order": 1
        },
        "summary": {
          "type": "string",
          "title": "Summary",
          "description": "Ticket summary",
          "order": 2
        },
        "details": {
          "type": "string",
          "title": "Details",
          "description": "Ticket details",
          "order": 3
        },
        "status": {
          "type": "string",
          "title": "Status",
          "description": "Ticket status",
          "order": 4
        },
        "status_id": {
          "type": "integer",
          "title": "Status ID",
          "description": "Ticket status ID",
          "order": 5
        },
        "priority": {
          "type": "string",
          "title": "Priority",
          "description": "Ticket priority",
          "order": 6
        },
        "priority_id": {
          "type": "integer",
          "title": "Priority ID",
          "description": "Ticket priority ID",
          "order": 7
        },
        "ticket_type": {
          "type": "string",
          "title": "Ticket Type",
          "description": "Ticket type",
          "order": 8
        },
        "ticket_type_id": {
          "type": "integer",
          "title": "Ticket Type ID",
          "description": "Ticket type ID",
          "order": 9
        },
        "agent": {
          "type": "string",
          "title": "Agent",
          "description": "Assigned agent name",
          "order": 10
        },
        "agent_id": {
          "type": "integer",
          "title": "Agent ID",
          "description": "Assigned agent ID",
          "order": 11
        },
        "team": {
          "type": "string",
          "title": "Team",
          "description": "Assigned team name",
          "order": 12
        },
        "team_id": {
          "type": "integer",
          "title": "Team ID",
          "description": "Assigned team ID",
          "order": 13
        },
        "created_date": {
          "type": "string",
          "title": "Created Date",
          "description": "Ticket creation date",
          "order": 14
        },
        "last_updated": {
          "type": "string",
          "title": "Last Updated",
          "description": "Ticket last update date",
          "order": 15
        },
        "client": {
          "type": "string",
          "title": "Client",
          "description": "Client name",
          "order": 16
        },
        "client_id": {
          "type": "integer",
          "title": "Client ID",
          "description": "Client ID",
          "order": 17
        },
        "site": {
          "type": "string",
          "title": "Site",
          "description": "Site name",
          "order": 18
        },
        "site_id": {
          "type": "integer",
          "title": "Site ID",
          "description": "Site ID",
          "order": 19
        },
        "user": {
          "type": "string",
          "title": "User",
          "description": "Reporting user name",
          "order": 20
        },
        "user_id": {
          "type": "integer",
          "title": "User ID",
          "description": "Reporting user ID",
          "order": 21
        },
        "category_1": {
          "type": "string",
          "title": "Category 1",
          "description": "Primary category",
          "order": 22
        },
        "category_2": {
          "type": "string",
          "title": "Category 2",
          "description": "Secondary category",
          "order": 23
        },
        "category_3": {
          "type": "string",
          "title": "Category 3",
          "description": "Tertiary category",
          "order": 24
        },
        "category_4": {
          "type": "string",
          "title": "Category 4",
          "description": "Quaternary category",
          "order": 25
        },
        "resolution": {
          "type": "string",
          "title": "Resolution",
          "description": "Ticket resolution",
          "order": 26
        },
        "url": {
          "type": "string",
          "title": "URL",
          "description": "Direct link to the ticket",
          "order": 27
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)