# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class CreateTicketInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
    {
      "type": "object",
      "title": "Variables",
      "properties": {
        "summary": {
          "type": "string",
          "title": "Summary",
          "description": "Ticket summary/title",
          "order": 1
        },
        "details": {
          "type": "string",
          "title": "Details",
          "description": "Detailed description of the ticket",
          "order": 2
        },
        "tickettype_id": {
          "type": "integer",
          "title": "Ticket Type ID",
          "description": "ID of the ticket type (uses connection default if not specified)",
          "order": 3
        },
        "priority_id": {
          "type": "integer",
          "title": "Priority ID",
          "description": "Priority level ID",
          "order": 4
        },
        "status_id": {
          "type": "integer",
          "title": "Status ID",
          "description": "Initial status ID",
          "default": 1,
          "order": 5
        },
        "category_id": {
          "type": "integer",
          "title": "Category ID",
          "description": "Ticket category ID",
          "order": 6
        },
        "agent_id": {
          "type": "integer",
          "title": "Agent ID",
          "description": "Assigned agent ID",
          "order": 7
        },
        "team_id": {
          "type": "integer",
          "title": "Team ID",
          "description": "Assigned team ID",
          "order": 8
        },
        "site_id": {
          "type": "integer",
          "title": "Site ID",
          "description": "Site/location ID",
          "order": 9
        },
        "user_id": {
          "type": "integer",
          "title": "User ID",
          "description": "End user ID (ticket requester)",
          "order": 10
        },
        "customfields": {
          "type": "array",
          "title": "Custom Fields",
          "description": "Array of custom field objects",
          "items": {
            "type": "object"
          },
          "order": 11
        }
      },
      "required": [
        "summary",
        "details"
      ],
      "definitions": {}
    }
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class CreateTicketOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
    {
      "type": "object",
      "title": "Variables",
      "properties": {
        "ticket": {
          "$ref": "#/definitions/ticket",
          "title": "Ticket",
          "description": "Created ticket details",
          "order": 1
        },
        "success": {
          "type": "boolean",
          "title": "Success",
          "description": "Was the operation successful",
          "order": 2
        }
      },
      "required": [
        "ticket",
        "success"
      ],
      "definitions": {
        "ticket": {
          "type": "object",
          "title": "ticket",
          "properties": {
            "id": {
              "type": "integer",
              "title": "ID",
              "description": "Ticket ID",
              "order": 1
            },
            "summary": {
              "type": "string",
              "title": "Summary", 
              "description": "Ticket summary",
              "order": 2
            },
            "details": {
              "type": "string",
              "title": "Details",
              "description": "Ticket details",
              "order": 3
            },
            "status_id": {
              "type": "integer",
              "title": "Status ID",
              "description": "Current status ID",
              "order": 4
            },
            "status_name": {
              "type": "string",
              "title": "Status Name",
              "description": "Current status name",
              "order": 5
            },
            "priority_id": {
              "type": "integer",
              "title": "Priority ID",
              "description": "Priority level ID",
              "order": 6
            },
            "agent_id": {
              "type": "integer",
              "title": "Agent ID",
              "description": "Assigned agent ID",
              "order": 7
            },
            "agent_name": {
              "type": "string",
              "title": "Agent Name",
              "description": "Assigned agent name",
              "order": 8
            },
            "datecreated": {
              "type": "string",
              "title": "Date Created",
              "description": "When the ticket was created",
              "order": 9
            },
            "url": {
              "type": "string",
              "title": "URL",
              "description": "Direct URL to ticket in HaloITSM",
              "order": 10
            }
          }
        }
      }
    }
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class Input:
    SUMMARY = "summary"
    DETAILS = "details"
    TICKETTYPE_ID = "tickettype_id"
    PRIORITY_ID = "priority_id"
    STATUS_ID = "status_id"
    CATEGORY_ID = "category_id"
    AGENT_ID = "agent_id"
    TEAM_ID = "team_id"
    SITE_ID = "site_id"
    USER_ID = "user_id"
    CUSTOMFIELDS = "customfields"


class Output:
    TICKET = "ticket"
    SUCCESS = "success"


class Component:
    DESCRIPTION = "Create a new ticket in HaloITSM"