# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class GetUserInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
    {
      "type": "object",
      "title": "Variables",
      "properties": {
        "user_id": {
          "type": "integer",
          "title": "User ID",
          "description": "ID of the user/agent to retrieve",
          "order": 1
        }
      },
      "required": ["user_id"],
      "definitions": {}
    }
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetUserOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
    {
      "type": "object",
      "title": "Variables",
      "properties": {
        "user": {
          "type": "object",
          "title": "User",
          "description": "User/agent details",
          "order": 1
        },
        "success": {
          "type": "boolean",
          "title": "Success",
          "description": "Whether the operation was successful",
          "order": 2
        }
      },
      "required": ["user", "success"],
      "definitions": {}
    }
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class Input:
    USER_ID = "user_id"


class Output:
    USER = "user"
    SUCCESS = "success"


class Component:
    DESCRIPTION = "Get user information by ID"
