# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class ConnectionSchema(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
    {
      "type": "object",
      "title": "Variables",
      "properties": {
        "client_id": {
          "type": "credential_secret_key",
          "title": "Client ID",
          "description": "OAuth2 Client ID for API authentication",
          "order": 1
        },
        "client_secret": {
          "type": "credential_secret_key", 
          "title": "Client Secret",
          "description": "OAuth2 Client Secret for API authentication",
          "order": 2
        },
        "authorization_server": {
          "type": "string",
          "title": "Authorization Server",
          "description": "HaloITSM OAuth2 authorization server URL",
          "order": 3
        },
        "resource_server": {
          "type": "string",
          "title": "Resource Server", 
          "description": "HaloITSM API resource server URL",
          "order": 4
        },
        "tenant": {
          "type": "string",
          "title": "Tenant",
          "description": "HaloITSM tenant identifier",
          "order": 5
        },
        "ssl_verify": {
          "type": "boolean",
          "title": "SSL Verify",
          "description": "Verify SSL certificate",
          "default": true,
          "order": 6
        }
      },
      "required": [
        "client_id",
        "client_secret", 
        "authorization_server",
        "resource_server",
        "tenant"
      ],
      "definitions": {}
    }
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class Input:
    CLIENT_ID = "client_id"
    CLIENT_SECRET = "client_secret"
    AUTHORIZATION_SERVER = "authorization_server"
    RESOURCE_SERVER = "resource_server"
    TENANT = "tenant"
    SSL_VERIFY = "ssl_verify"