# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class TicketStatusChangedInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
    {
      "type": "object",
      "title": "Variables",
      "properties": {
        "ticket_id": {
          "type": "integer",
          "title": "Ticket ID",
          "description": "Only trigger for specific ticket ID (optional)",
          "order": 1
        },
        "new_status_id": {
          "type": "integer",
          "title": "New Status ID",
          "description": "Only trigger when status changes to this value (optional)",
          "order": 2
        }
      },
      "required": [],
      "definitions": {}
    }
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class TicketStatusChangedOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
    {
      "type": "object",
      "title": "Variables",
      "properties": {
        "ticket": {
          "$ref": "#/definitions/ticket",
          "title": "Ticket",
          "description": "Ticket details with new status",
          "order": 1
        },
        "old_status_id": {
          "type": "integer",
          "title": "Old Status ID",
          "description": "Previous status ID",
          "order": 2
        },
        "new_status_id": {
          "type": "integer",
          "title": "New Status ID",
          "description": "New status ID",
          "order": 3
        }
      },
      "required": [
        "ticket",
        "old_status_id",
        "new_status_id"
      ],
      "definitions": {
        "ticket": {
          "type": "object",
          "title": "ticket",
          "properties": {
            "id": {
              "type": "integer",
              "title": "ID",
              "description": "Ticket ID",
              "order": 1
            },
            "summary": {
              "type": "string",
              "title": "Summary",
              "description": "Ticket summary",
              "order": 2
            }
          }
        }
      }
    }
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class Input:
    TICKET_ID = "ticket_id"
    NEW_STATUS_ID = "new_status_id"


class Output:
    TICKET = "ticket"
    OLD_STATUS_ID = "old_status_id"
    NEW_STATUS_ID = "new_status_id"


class Component:
    DESCRIPTION = "Triggers specifically when ticket status changes (webhook)"
