# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class UpdateTicketInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
    {
      "type": "object",
      "title": "Variables",
      "properties": {
        "ticket_id": {
          "type": "integer",
          "title": "Ticket ID",
          "description": "ID of the ticket to update",
          "order": 1
        },
        "summary": {
          "type": "string",
          "title": "Summary",
          "description": "Updated ticket summary",
          "order": 2
        },
        "details": {
          "type": "string",
          "title": "Details",
          "description": "Updated ticket details",
          "order": 3
        },
        "status_id": {
          "type": "integer",
          "title": "Status ID",
          "description": "Updated status ID",
          "order": 4
        },
        "priority_id": {
          "type": "integer",
          "title": "Priority ID",
          "description": "Updated priority ID",
          "order": 5
        },
        "agent_id": {
          "type": "integer",
          "title": "Agent ID",
          "description": "Updated assigned agent ID",
          "order": 6
        },
        "customfields": {
          "type": "array",
          "title": "Custom Fields",
          "description": "Array of custom field objects to update",
          "items": {
            "type": "object"
          },
          "order": 7
        }
      },
      "required": [
        "ticket_id"
      ],
      "definitions": {}
    }
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class UpdateTicketOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
    {
      "type": "object",
      "title": "Variables",
      "properties": {
        "ticket": {
          "$ref": "#/definitions/ticket",
          "title": "Ticket",
          "description": "Updated ticket details",
          "order": 1
        },
        "success": {
          "type": "boolean",
          "title": "Success",
          "description": "Was the operation successful",
          "order": 2
        }
      },
      "required": [
        "ticket",
        "success"
      ],
      "definitions": {
        "ticket": {
          "type": "object",
          "title": "ticket",
          "properties": {
            "id": {
              "type": "integer",
              "title": "ID",
              "description": "Ticket ID",
              "order": 1
            },
            "summary": {
              "type": "string",
              "title": "Summary",
              "description": "Ticket summary",
              "order": 2
            }
          }
        }
      }
    }
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class Input:
    TICKET_ID = "ticket_id"
    SUMMARY = "summary"
    DETAILS = "details"
    STATUS_ID = "status_id"
    PRIORITY_ID = "priority_id"
    AGENT_ID = "agent_id"
    CUSTOMFIELDS = "customfields"


class Output:
    TICKET = "ticket"
    SUCCESS = "success"


class Component:
    DESCRIPTION = "Update an existing ticket in HaloITSM"