# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Get a specific HaloITSM ticket by ID"


class Input:
    TICKET_ID = "ticket_id"


class Output:
    SUCCESS = "success"
    TICKET = "ticket"


class GetTicketInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "ticket_id": {
      "type": "integer",
      "title": "Ticket ID",
      "description": "The ID of the ticket to retrieve",
      "order": 1
    }
  },
  "required": [
    "ticket_id"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetTicketOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "success": {
      "type": "boolean",
      "title": "Success",
      "description": "Whether the operation was successful",
      "order": 1
    },
    "ticket": {
      "$ref": "#/definitions/ticket",
      "title": "Ticket",
      "description": "The retrieved ticket",
      "order": 2
    }
  },
  "required": [
    "success",
    "ticket"
  ],
  "definitions": {
    "ticket": {
      "type": "object",
      "title": "ticket",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "Ticket ID",
          "order": 1
        },
        "summary": {
          "type": "string",
          "title": "Summary", 
          "description": "Ticket summary",
          "order": 2
        },
        "details": {
          "type": "string",
          "title": "Details",
          "description": "Ticket details",
          "order": 3
        },
        "status_id": {
          "type": "integer",
          "title": "Status ID",
          "description": "Status ID",
          "order": 4
        },
        "status_name": {
          "type": "string", 
          "title": "Status Name",
          "description": "Status name",
          "order": 5
        },
        "priority_id": {
          "type": "integer",
          "title": "Priority ID", 
          "description": "Priority ID",
          "order": 6
        },
        "priority_name": {
          "type": "string",
          "title": "Priority Name",
          "description": "Priority name",
          "order": 7
        },
        "agent_id": {
          "type": "integer",
          "title": "Agent ID",
          "description": "Assigned agent ID",
          "order": 8
        },
        "agent_name": {
          "type": "string",
          "title": "Agent Name", 
          "description": "Assigned agent name",
          "order": 9
        },
        "ticket_type_id": {
          "type": "integer",
          "title": "Ticket Type ID",
          "description": "Ticket type ID",
          "order": 10
        },
        "ticket_type_name": {
          "type": "string",
          "title": "Ticket Type Name",
          "description": "Ticket type name", 
          "order": 11
        },
        "date_created": {
          "type": "string",
          "title": "Date Created",
          "description": "Date ticket was created",
          "order": 12
        },
        "date_updated": {
          "type": "string",
          "title": "Date Updated", 
          "description": "Date ticket was last updated",
          "order": 13
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)