# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class TicketUpdatedInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
    {
      "type": "object",
      "title": "Variables",
      "properties": {
        "ticket_id": {
          "type": "integer",
          "title": "Ticket ID",
          "description": "Only trigger for specific ticket ID (optional)",
          "order": 1
        },
        "status_changed": {
          "type": "boolean",
          "title": "Status Changed",
          "description": "Only trigger when status changes",
          "default": false,
          "order": 2
        }
      },
      "required": [],
      "definitions": {}
    }
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class TicketUpdatedOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
    {
      "type": "object",
      "title": "Variables",
      "properties": {
        "ticket": {
          "$ref": "#/definitions/ticket",
          "title": "Ticket",
          "description": "Updated ticket details",
          "order": 1
        },
        "previous_status_id": {
          "type": "integer",
          "title": "Previous Status ID",
          "description": "Previous status ID before update",
          "order": 2
        }
      },
      "required": [
        "ticket"
      ],
      "definitions": {
        "ticket": {
          "type": "object",
          "title": "ticket",
          "properties": {
            "id": {
              "type": "integer",
              "title": "ID",
              "description": "Ticket ID",
              "order": 1
            },
            "summary": {
              "type": "string",
              "title": "Summary",
              "description": "Ticket summary",
              "order": 2
            }
          }
        }
      }
    }
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class Input:
    TICKET_ID = "ticket_id"
    STATUS_CHANGED = "status_changed"


class Output:
    TICKET = "ticket"
    PREVIOUS_STATUS_ID = "previous_status_id"


class Component:
    DESCRIPTION = "Triggers when a ticket is updated in HaloITSM (webhook)"
