# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class TicketCreatedInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
    {
      "type": "object",
      "title": "Variables",
      "properties": {
        "tickettype_id": {
          "type": "integer",
          "title": "Ticket Type ID",
          "description": "Only trigger for specific ticket type (optional)",
          "order": 1
        },
        "priority_id": {
          "type": "integer",
          "title": "Priority ID",
          "description": "Only trigger for specific priority (optional)",
          "order": 2
        }
      },
      "required": [],
      "definitions": {}
    }
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class TicketCreatedOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
    {
      "type": "object",
      "title": "Variables",
      "properties": {
        "ticket": {
          "$ref": "#/definitions/ticket",
          "title": "Ticket",
          "description": "Newly created ticket details",
          "order": 1
        }
      },
      "required": [
        "ticket"
      ],
      "definitions": {
        "ticket": {
          "type": "object",
          "title": "ticket",
          "properties": {
            "id": {
              "type": "integer",
              "title": "ID",
              "description": "Ticket ID",
              "order": 1
            },
            "summary": {
              "type": "string",
              "title": "Summary",
              "description": "Ticket summary",
              "order": 2
            }
          }
        }
      }
    }
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class Input:
    TICKETTYPE_ID = "tickettype_id"
    PRIORITY_ID = "priority_id"


class Output:
    TICKET = "ticket"


class Component:
    DESCRIPTION = "Triggers when a new ticket is created in HaloITSM (webhook)"