# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class GetAgentInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
    {
      "type": "object",
      "title": "Variables",
      "properties": {
        "agent_id": {
          "type": "integer",
          "title": "Agent ID",
          "description": "ID of the agent to retrieve",
          "order": 1
        }
      },
      "required": ["agent_id"],
      "definitions": {}
    }
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetAgentOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
    {
      "type": "object",
      "title": "Variables",
      "properties": {
        "agent": {
          "type": "object",
          "title": "Agent",
          "description": "Agent details",
          "order": 1
        },
        "success": {
          "type": "boolean",
          "title": "Success",
          "description": "Whether the operation was successful",
          "order": 2
        }
      },
      "required": ["agent", "success"],
      "definitions": {}
    }
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class Input:
    AGENT_ID = "agent_id"


class Output:
    AGENT = "agent"
    SUCCESS = "success"


class Component:
    DESCRIPTION = "Get agent information by ID"
