# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
from setuptools import setup, find_packages


setup(name="haloitsm-derricksmith-plugin",
      version="2.1.0",
      description="Manage tickets and automate workflows with HaloITSM service desk",
      author="derricksmith",
      author_email="",
      url="",
      packages=find_packages(),
      install_requires=['insightconnect-plugin-runtime'],  # Add third-party dependencies to requirements.txt, not here!
      entry_points={"console_scripts": ["icon_haloitsm = bin.icon_haloitsm:main"]}
      )