# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class ConnectionSchema(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
    {
      "type": "object",
      "title": "Variables",
      "properties": {
        "client_id": {
          "type": "string",
          "title": "Client ID",
          "description": "OAuth2 Client ID for API authentication",
          "order": 1
        },
        "client_secret": {
          "type": "credential_secret_key", 
          "title": "Client Secret",
          "description": "OAuth2 Client Secret for API authentication",
          "order": 2
        },
        "authorization_server": {
          "type": "string",
          "title": "Authorization Server",
          "description": "HaloITSM OAuth2 authorization server URL",
          "order": 3
        },
        "resource_server": {
          "type": "string",
          "title": "Resource Server", 
          "description": "HaloITSM API resource server URL",
          "order": 4
        },
        "tenant": {
          "type": "string",
          "title": "Tenant",
          "description": "HaloITSM tenant identifier",
          "order": 5
        },
        "ssl_verify": {
          "type": "boolean",
          "title": "SSL Verify",
          "description": "Verify SSL certificate",
          "default": true,
          "order": 6
        },
        "default_ticket_type_id": {
          "type": "integer",
          "title": "Default Ticket Type ID",
          "description": "Default ticket type ID to use when creating tickets (can be overridden per action)",
          "order": 7
        },
        "default_priority_id": {
          "type": "integer",
          "title": "Default Priority ID", 
          "description": "Default priority ID to use when creating tickets (can be overridden per action)",
          "order": 8
        },
        "default_team_id": {
          "type": "integer",
          "title": "Default Team ID",
          "description": "Default team ID to assign tickets to (can be overridden per action)",
          "order": 9
        },
        "default_agent_id": {
          "type": "integer",
          "title": "Default Agent ID",
          "description": "Default agent ID to assign tickets to (can be overridden per action)",
          "order": 10
        },
        "default_category_id": {
          "type": "integer",
          "title": "Default Category ID",
          "description": "Default category ID for tickets (can be overridden per action)",
          "order": 11
        }
      },
      "required": [
        "client_id",
        "client_secret", 
        "authorization_server",
        "resource_server",
        "tenant"
      ],
      "definitions": {}
    }
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class Input:
    CLIENT_ID = "client_id"
    CLIENT_SECRET = "client_secret"
    AUTHORIZATION_SERVER = "authorization_server"
    RESOURCE_SERVER = "resource_server"
    TENANT = "tenant"
    SSL_VERIFY = "ssl_verify"
    DEFAULT_TICKET_TYPE_ID = "default_ticket_type_id"
    DEFAULT_PRIORITY_ID = "default_priority_id"
    DEFAULT_TEAM_ID = "default_team_id"
    DEFAULT_AGENT_ID = "default_agent_id"
    DEFAULT_CATEGORY_ID = "default_category_id"